{
 "title": "Manager Service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(manager_service_errors_total[10s])) by (handler)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(manager_service_grpc_response_time_bucket[$__rate_interval])) by (le))\r\n",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(manager_service_grpc_response_time_bucket[$__rate_interval])) by (le))\r\n",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(manager_service_grpc_response_time_bucket[$__rate_interval])) by (le))\r\n",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Total Accepted Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "manager_service_total_accepted_orders",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Issued To Client Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "manager_service_total_issued_orders",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Refunded Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "manager_service_total_refunded_orders",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Returned Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "manager_service_total_returned_orders",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}