alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'manager_service'
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: [ 'manager-service:8080' ]

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'node-exporter:9100' ]