// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.14.0
// source: manager-service/v1/manager-service.proto

package manager_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagerService_AddOrderV1_FullMethodName    = "/manager.ManagerService/AddOrderV1"
	ManagerService_RefundV1_FullMethodName      = "/manager.ManagerService/RefundV1"
	ManagerService_GiveOrdersV1_FullMethodName  = "/manager.ManagerService/GiveOrdersV1"
	ManagerService_ReturnV1_FullMethodName      = "/manager.ManagerService/ReturnV1"
	ManagerService_ViewOrdersV1_FullMethodName  = "/manager.ManagerService/ViewOrdersV1"
	ManagerService_ViewRefundsV1_FullMethodName = "/manager.ManagerService/ViewRefundsV1"
)

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerServiceClient interface {
	AddOrderV1(ctx context.Context, in *AddOrderRequestV1, opts ...grpc.CallOption) (*AddOrderResponseV1, error)
	RefundV1(ctx context.Context, in *RefundRequestV1, opts ...grpc.CallOption) (*RefundResponseV1, error)
	GiveOrdersV1(ctx context.Context, in *GiveOrdersRequestV1, opts ...grpc.CallOption) (*GiveOrdersResponseV1, error)
	ReturnV1(ctx context.Context, in *ReturnRequestV1, opts ...grpc.CallOption) (*ReturnResponseV1, error)
	ViewOrdersV1(ctx context.Context, in *ViewOrdersRequestV1, opts ...grpc.CallOption) (*ViewOrdersResponseV1, error)
	ViewRefundsV1(ctx context.Context, in *ViewRefundsRequestV1, opts ...grpc.CallOption) (*ViewRefundsResponseV1, error)
}

type managerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerServiceClient(cc grpc.ClientConnInterface) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) AddOrderV1(ctx context.Context, in *AddOrderRequestV1, opts ...grpc.CallOption) (*AddOrderResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOrderResponseV1)
	err := c.cc.Invoke(ctx, ManagerService_AddOrderV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) RefundV1(ctx context.Context, in *RefundRequestV1, opts ...grpc.CallOption) (*RefundResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundResponseV1)
	err := c.cc.Invoke(ctx, ManagerService_RefundV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GiveOrdersV1(ctx context.Context, in *GiveOrdersRequestV1, opts ...grpc.CallOption) (*GiveOrdersResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GiveOrdersResponseV1)
	err := c.cc.Invoke(ctx, ManagerService_GiveOrdersV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ReturnV1(ctx context.Context, in *ReturnRequestV1, opts ...grpc.CallOption) (*ReturnResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnResponseV1)
	err := c.cc.Invoke(ctx, ManagerService_ReturnV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ViewOrdersV1(ctx context.Context, in *ViewOrdersRequestV1, opts ...grpc.CallOption) (*ViewOrdersResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewOrdersResponseV1)
	err := c.cc.Invoke(ctx, ManagerService_ViewOrdersV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ViewRefundsV1(ctx context.Context, in *ViewRefundsRequestV1, opts ...grpc.CallOption) (*ViewRefundsResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewRefundsResponseV1)
	err := c.cc.Invoke(ctx, ManagerService_ViewRefundsV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
// All implementations must embed UnimplementedManagerServiceServer
// for forward compatibility.
type ManagerServiceServer interface {
	AddOrderV1(context.Context, *AddOrderRequestV1) (*AddOrderResponseV1, error)
	RefundV1(context.Context, *RefundRequestV1) (*RefundResponseV1, error)
	GiveOrdersV1(context.Context, *GiveOrdersRequestV1) (*GiveOrdersResponseV1, error)
	ReturnV1(context.Context, *ReturnRequestV1) (*ReturnResponseV1, error)
	ViewOrdersV1(context.Context, *ViewOrdersRequestV1) (*ViewOrdersResponseV1, error)
	ViewRefundsV1(context.Context, *ViewRefundsRequestV1) (*ViewRefundsResponseV1, error)
	mustEmbedUnimplementedManagerServiceServer()
}

// UnimplementedManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerServiceServer struct{}

func (UnimplementedManagerServiceServer) AddOrderV1(context.Context, *AddOrderRequestV1) (*AddOrderResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrderV1 not implemented")
}
func (UnimplementedManagerServiceServer) RefundV1(context.Context, *RefundRequestV1) (*RefundResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundV1 not implemented")
}
func (UnimplementedManagerServiceServer) GiveOrdersV1(context.Context, *GiveOrdersRequestV1) (*GiveOrdersResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveOrdersV1 not implemented")
}
func (UnimplementedManagerServiceServer) ReturnV1(context.Context, *ReturnRequestV1) (*ReturnResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnV1 not implemented")
}
func (UnimplementedManagerServiceServer) ViewOrdersV1(context.Context, *ViewOrdersRequestV1) (*ViewOrdersResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewOrdersV1 not implemented")
}
func (UnimplementedManagerServiceServer) ViewRefundsV1(context.Context, *ViewRefundsRequestV1) (*ViewRefundsResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewRefundsV1 not implemented")
}
func (UnimplementedManagerServiceServer) mustEmbedUnimplementedManagerServiceServer() {}
func (UnimplementedManagerServiceServer) testEmbeddedByValue()                        {}

// UnsafeManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServiceServer will
// result in compilation errors.
type UnsafeManagerServiceServer interface {
	mustEmbedUnimplementedManagerServiceServer()
}

func RegisterManagerServiceServer(s grpc.ServiceRegistrar, srv ManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagerService_ServiceDesc, srv)
}

func _ManagerService_AddOrderV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).AddOrderV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_AddOrderV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).AddOrderV1(ctx, req.(*AddOrderRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_RefundV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).RefundV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_RefundV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).RefundV1(ctx, req.(*RefundRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GiveOrdersV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GiveOrdersRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GiveOrdersV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GiveOrdersV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GiveOrdersV1(ctx, req.(*GiveOrdersRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ReturnV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ReturnV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ReturnV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ReturnV1(ctx, req.(*ReturnRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ViewOrdersV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewOrdersRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ViewOrdersV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ViewOrdersV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ViewOrdersV1(ctx, req.(*ViewOrdersRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ViewRefundsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewRefundsRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ViewRefundsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ViewRefundsV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ViewRefundsV1(ctx, req.(*ViewRefundsRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagerService_ServiceDesc is the grpc.ServiceDesc for ManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrderV1",
			Handler:    _ManagerService_AddOrderV1_Handler,
		},
		{
			MethodName: "RefundV1",
			Handler:    _ManagerService_RefundV1_Handler,
		},
		{
			MethodName: "GiveOrdersV1",
			Handler:    _ManagerService_GiveOrdersV1_Handler,
		},
		{
			MethodName: "ReturnV1",
			Handler:    _ManagerService_ReturnV1_Handler,
		},
		{
			MethodName: "ViewOrdersV1",
			Handler:    _ManagerService_ViewOrdersV1_Handler,
		},
		{
			MethodName: "ViewRefundsV1",
			Handler:    _ManagerService_ViewRefundsV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager-service/v1/manager-service.proto",
}
